version: '3.7'

services:
  nginx:
    image: nginx
    container_name: docker_nginx
    ports:
      - ${WEB_PORT}
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app
    depends_on:
      - php

  php:
    image: php:8.0-fpm-alpine3.12
    container_name: docker_php
    restart: always
    volumes:
      - .:/var/www/html:delegated
    networks:
      - app

  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql: null
